.TH "linked_list_node" 3 "Thu Jun 13 2013" "Version 0.1" "C Hash Map" \" -*- nroff -*-
.ad l
.nh
.SH NAME
linked_list_node \- 
.PP
Linked list node structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <linked_list\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct _linked_list_node * \fBnext\fP"
.br
.RI "\fIPointer to the next node\&. \fP"
.ti -1c
.RI "void * \fBdata\fP"
.br
.RI "\fIPointer to data\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Linked list node structure\&. 
.PP
Definition at line 29 of file linked_list\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C Hash Map from the source code\&.
