.TH "linked_list" 3 "Thu Jun 13 2013" "Version 0.1" "C Hash Map" \" -*- nroff -*-
.ad l
.nh
.SH NAME
linked_list \- 
.PP
Linked list object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <linked_list\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBlinked_list_node\fP * \fBhead\fP"
.br
.RI "\fIPointer to sentinel node\&. \fP"
.ti -1c
.RI "\fBlinked_list_comparator\fP \fBcomparator\fP"
.br
.RI "\fIComparator function used for \fBlinked_list_remove_first\fP\&. \fP"
.ti -1c
.RI "\fBlinked_list_destructor\fP \fBfree_data\fP"
.br
.RI "\fIFunction used to free data\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Linked list object\&. 
.PP
Definition at line 39 of file linked_list\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C Hash Map from the source code\&.
